error: Restore error_printf()'s function comment
Lost in commit 397d30e9401 (qemu-error: remove dependency of stubs on
monitor) many moons ago.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Message-ID: <20260114124713.3308719-3-armbru@redhat.com>
Reviewed-by: Daniel P. Berrangé <berrange@redhat.com>
[Trivial conflict with commit a582a5784e5f (monitor: move
error_vprintf back to error-report.c) resolved]